import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import QRCode from 'qrcode'
import Art from './Art.jsx'
import { questions, archetypes, calculateIdentity, decodeAnswers, encodeAnswers } from './identity.js'
import { exportCard } from './exportCard.js'
import './style.css'

function routeFromHash() {
  const hash=decodeURIComponent(location.hash.slice(1))
  if (hash.startsWith('/result/')) { const answers=decodeAnswers(hash.split('/')[2]); if(answers) return { page:'result', answers } }
  if (hash==='/poster') return {page:'poster'}
  if (hash==='/quiz') return {page:'quiz'}
  return {page:'home'}
}
function navigate(path) { location.hash=path; window.scrollTo({top:0,behavior:'smooth'}) }
function Brand() { return <button className="brand" onClick={()=>navigate('/')} aria-label="返回首页"><span className="brand-mark">✳</span><span><strong>东海幻想</strong><small>AIGC IDENTITY LAB</small></span></button> }
function Header() { return <header className="site-header"><div className="container header-inner"><Brand/><nav><button onClick={()=>navigate('/')}>探索首页</button><button onClick={()=>navigate('/poster')}>活动海报</button><button className="nav-cta" onClick={()=>navigate('/quiz')}>开始测试 <span>↗</span></button></nav></div></header> }
function Footer() { return <footer><div className="container footer-inner"><span>✳ 东海幻想身份生成器</span><span>AIGC 绘画社互动项目 · 原创程序化视觉</span><span>© 2026 Identity Lab</span></div></footer> }
function Button({children,onClick,secondary=false,className='',disabled=false}) { return <button type="button" className={`button ${secondary?'button-secondary':''} ${className}`} onClick={onClick} disabled={disabled}>{children}</button> }
function GalleryCard({identity,index}) {return <article className="gallery-card" style={{'--card-accent':identity.accent}}><div className="gallery-art"><Art identity={identity} id={`gallery-${index}`}/><span className="gallery-index">0{index+1} / VISUAL STUDY</span></div><div className="gallery-info"><span>{identity.tag}</span><h3>{identity.name}</h3><p>{identity.prompt}</p></div></article>}

function Home() { const examples=[archetypes[0],archetypes[1],archetypes[3],archetypes[5],archetypes[6],archetypes[7]]; return <>
  <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> AIGC 绘画社 · 互动体验企划</div><h1>如果你生活在<br/><em>另一个世界</em><br/>你会是谁？</h1><p className="hero-lead">五个选择，一张属于你的异世界校园身份卡。让想象力为你命名，让一段故事从这里开始。</p><div className="hero-actions"><Button onClick={()=>navigate('/quiz')}>探索我的身份 <span>↗</span></Button><button className="text-button" onClick={()=>document.getElementById('gallery')?.scrollIntoView({behavior:'smooth'})}>浏览幻想画廊 <span>↓</span></button></div><div className="hero-meta"><span>✧ 5 个轻量问题</span><span>◈ 12 种身份原型</span><span>◎ 免费保存分享</span></div></div><div className="hero-visual"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-card"><Art identity={archetypes[0]} id="hero-art"/><div className="hero-card-caption"><span>PERSONA PREVIEW / 001</span><strong>机械星图师</strong></div></div><div className="floating-label top">IDENTITY<br/>DISCOVERED</div><div className="floating-label bottom">12 <span>ALTER EGO<br/>ARCHETYPES</span></div></div></section>
  <section className="intro-strip"><div className="container strip-inner"><span>一个选择，开启一段故事</span><span>✦</span><span>想象 × 设计 × 程序化艺术</span><span>✦</span><span>你的身份，由你定义</span></div></section>
  <section className="section container" id="gallery"><div className="section-heading"><div><div className="eyebrow">01 / THE GALLERY</div><h2>幻想作品展示墙<span>✳</span></h2><p>六张由项目自身绘制的角色概念视觉。每一道光，都从一个答案开始。</p></div><button className="ghost-link" onClick={()=>navigate('/quiz')}>寻找我的作品 ↗</button></div><div className="gallery-grid">{examples.map((item,i)=><GalleryCard identity={item} index={i} key={item.name}/>)}</div></section>
  <section className="process-section"><div className="container process-inner"><div><div className="eyebrow">02 / HOW IT WORKS</div><h2>你来选择，<br/>世界为你成形。</h2><p>从专业、性格、世界观、代表色到偏好的能力，系统将你的选择组合为独一份的身份档案。</p><Button onClick={()=>navigate('/quiz')}>现在开始 <span>↗</span></Button></div><div className="steps"><div><b>01</b><span><strong>回答五个问题</strong><small>约 30 秒，跟着直觉选择</small></span><i>↗</i></div><div><b>02</b><span><strong>解锁身份档案</strong><small>名称、故事、技能与四项属性</small></span><i>↗</i></div><div><b>03</b><span><strong>保存分享卡片</strong><small>下载 PNG，把幻想带走</small></span><i>↗</i></div></div></div></section>
  <section className="cta-section container"><div className="cta-glow"/><div className="eyebrow">AIGC 绘画社 · 线下互动体验</div><h2>下一个故事，<br/><em>从你开始。</em></h2><p>无需登录，立即生成你的异世界身份。</p><Button onClick={()=>navigate('/quiz')}>生成我的身份 <span>↗</span></Button></section>
</>}

function Quiz({initialAnswers=null}) {const [step,setStep]=useState(0);const [answers,setAnswers]=useState(initialAnswers||Array(5).fill(null));const question=questions[step]; const selected=answers[step]; function choose(i){setAnswers(prev=>{const next=[...prev];next[step]=i;return next})} function next(){if(selected==null)return;if(step<4)setStep(step+1);else navigate(`/result/${encodeAnswers(answers)}`)} return <section className="quiz-page container"><div className="quiz-top"><button className="back-link" onClick={()=>step?setStep(step-1):navigate('/')}>← {step?'上一题':'返回首页'}</button><span>IDENTITY SCAN / {String(step+1).padStart(2,'0')} OF 05</span></div><div className="progress" aria-label={`进度 ${step+1}/5`}><span style={{width:`${(step+1)*20}%`}}/></div><div className="quiz-content"><div className="eyebrow">{question.eyebrow}</div><h1>{question.title}</h1><p>凭第一直觉选择，答案没有对错。</p><div className="options">{question.options.map((option,i)=><button className={`option ${selected===i?'selected':''}`} onClick={()=>choose(i)} key={option.label} aria-pressed={selected===i}><span className="option-icon" style={option.hex?{'--color':option.hex}:undefined}>{option.icon}</span><span><strong>{option.label}</strong><small>{option.hint}</small></span><span className="option-check">{selected===i?'✓':'↗'}</span></button>)}</div><div className="quiz-bottom"><span>QUESTION {String(step+1).padStart(2,'0')} / 05</span><Button onClick={next} disabled={selected==null}>{step===4?'解锁我的身份':'下一步'} <span>↗</span></Button></div></div></section>}

function Result({answers}) {const identity=useMemo(()=>calculateIdentity(answers),[answers]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');if(!identity)return null;async function download(){try{setBusy(true);setMessage('');const blob=await exportCard(identity);if(!blob)throw Error('PNG unavailable');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`东海幻想身份卡-${identity.name}-${identity.serial}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setMessage('分享卡已保存为 PNG')}catch(e){setMessage('导出失败，请换用现代浏览器重试。')}finally{setBusy(false)}} async function share(){const url=location.href;try{if(navigator.share){await navigator.share({title:`我的异世界身份：${identity.name}`,text:'来测测你的东海幻想身份',url})}else{await navigator.clipboard.writeText(url);setMessage('结果链接已复制')}}catch(e){if(e.name!=='AbortError')setMessage('分享未完成，可直接复制浏览器地址。')}}return <section className="result-page container"><div className="result-heading"><div className="eyebrow"><span className="live-dot"/> IDENTITY DISCOVERED / #{identity.serial}</div><h1>你的异世界身份已觉醒。</h1><p>这是一份由你的五个选择生成的专属幻想档案。</p></div><div className="result-layout"><div className="result-art" id="result-art"><Art identity={identity} id="result-illustration"/><span className="art-stamp">ORIGINAL<br/>PERSONA ART</span></div><div className="result-panel" style={{'--accent':identity.color}}><div className="result-tags"><span>{identity.tag}</span><span>NO. {identity.serial}</span></div><h2>{identity.name}</h2><p className="result-blurb">{identity.blurb}</p><div className="profile-chips"><span>✳ {identity.field}系</span><span>◈ {identity.temperament}性格</span><span>↗ {identity.constellation}能力</span></div><div className="stats"><h3>角色属性 <small>PERSONA STATS</small></h3>{['创造力','洞察力','行动力','共鸣力'].map((label,i)=><div className="stat" key={label}><span>{label}</span><div className="stat-track"><i style={{width:`${identity.stats[i]}%`}}/></div><b>{identity.stats[i]}</b></div>)}</div><div className="skill"><span>✦ 专属技能</span><strong>{identity.skill}</strong></div><div className="prompt"><div><span>PROMPT FRAGMENT</span><button onClick={async()=>{try{await navigator.clipboard.writeText(identity.prompt);setMessage('Prompt 已复制')}catch{setMessage('复制失败，请手动选择文本。')}}}>复制 ↗</button></div><code>{identity.prompt}</code></div></div></div><div className="result-actions"><Button onClick={download} disabled={busy}>{busy?'正在生成 PNG…':'↓ 生成分享卡'}</Button><Button secondary onClick={()=>navigate('/quiz')}>↺ 再测一次</Button><button className="text-button" onClick={share}>分享结果链接 ↗</button></div>{message&&<div className="toast" role="status">{message}</div>}<p className="result-note">图片由本项目原创 SVG 与 Canvas 生成。相同选择会得到相同结果。</p></section>}

function Poster() {const [qr,setQr]=useState('');const siteUrl=location.origin+location.pathname.replace(/index\.html$/,'');useEffect(()=>{QRCode.toDataURL(siteUrl,{width:500,margin:1,color:{dark:'#0b1730',light:'#ffffff'},errorCorrectionLevel:'H'}).then(setQr)},[siteUrl]);return <section className="poster-page container"><div className="poster-toolbar"><div><div className="eyebrow">EVENT DISPLAY / PRINT MODE</div><h1>现场展示海报</h1><p>扫描下方二维码，直接进入身份生成器。</p></div><Button secondary onClick={()=>window.print()}>打印海报 ↗</Button></div><div className="poster"><div className="poster-dots"/><div className="poster-upper"><div className="poster-brand">✳ 东海幻想 <span>IDENTITY LAB</span></div><span>AIGC 绘画社 · 互动体验</span></div><div className="poster-main"><div className="eyebrow">FIND YOUR OTHER SELF</div><h2>扫码测试：<br/>如果你生活在<br/><em>另一个世界，</em><br/>你会是什么身份？</h2><p>五个选择，解锁专属异世界校园身份卡。</p></div><div className="poster-bottom"><div className="qr-frame">{qr?<img src={qr} alt="进入身份生成器的二维码"/>:<span>正在生成二维码…</span>}</div><div><strong>扫描二维码<br/>开启身份档案 ↗</strong><small>{siteUrl}</small></div></div><div className="poster-footer">NO LOGIN · FREE TO PLAY · SAVE YOUR CARD <span>✦</span> AIGC IDENTITY LAB</div></div></section>}

function App(){const [route,setRoute]=useState(routeFromHash);useEffect(()=>{const listener=()=>setRoute(routeFromHash());addEventListener('hashchange',listener);return()=>removeEventListener('hashchange',listener)},[]);return <><div className="ambient ambient-one"/><div className="ambient ambient-two"/><Header/><main>{route.page==='home'?<Home/>:route.page==='quiz'?<Quiz key="quiz"/>:route.page==='poster'?<Poster/>:<Result answers={route.answers}/>}</main><Footer/></>}

createRoot(document.getElementById('root')).render(<App/>)
